drive:
    freq_hertz: 20
    verbose: False
    verbosity: 20
parts:
 - joystick:
      type: PS3Controller
      arguments:
        scale_throttle_forward: 1.0
        scale_throttle_back: 1.0
        scale_steer_left: 1.0
        scale_steer_right: 1.0
 - actuator:
        type: ThrottleController
        arguments:
          controller_select: PCA
          channel: 0
          full_reverse_pulse:     350
          full_forward_pulse:     400
          neutral_pulse:          370
 - actuator:
        type: SteeringController
        arguments:
          controller_select: PCA
          channel: 1
          full_left_pulse:    425
          full_right_pulse:   295         
